### ISSUE TITLE
ykla: Update 5. The X Window System (1811 - 2212)

### ISSUE THREAD

**Issue by yzgyyang** [yzgyyang/freebsd-doc-cn#3]
@ykla Which chapter do you want to take on?

For available chapters and current status, please view: 
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md

**Comment by DarkGost** [comment]
不知道从哪里入手啊

**Comment by ykla** [comment]
I want to translate 

 5. The X Window System

I think it's OK.

**Comment by ykla** [comment]
@yzgyyang

**Comment by yzgyyang** [comment]
@DarkGost 把 repo 设置好，然后把自己加进 Contributor 里，然后我们会讨论你想要弄哪一章
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/translators_guide.md

示例的 pull request 可以看: https://github.com/yzgyyang/freebsd-doc-cn/pull/2

**Comment by yzgyyang** [comment]
@ykla 好的，你可以先下一个 PO 编辑器（例如 poedit）熟悉一下操作，然后尝试用其打开
 `projects/books/handbook/zh_CN.po`。稍后我将会把要翻译的行号告诉你。

翻译的话，不用完全自己打，可以参照现有的原文和翻译。如果内容没有过期则可以直接用，否则可以稍微修改一下。
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md#references

**Comment by ykla** [comment]
@yzgyyang 繁体大部分可用，准备简体化

**Comment by yzgyyang** [comment]
@ykla  需要翻译的行数为 1811-2212，状态已经更新，可以开始了。 😆 
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md

繁体转简体是可以的，但是一定要注意很多惯用法上的不同，建议还是人工从严把关为好。
