### ISSUE TITLE
hacking: Update 8. Configuring the FreeBSD Kernel (2779 - 2867)

### ISSUE THREAD

**Issue by yzgyyang** [yzgyyang/freebsd-doc-cn#4]
@maojun1998 Which chapter do you want to take on?

For available chapters and current status, please view:
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md

**Comment by maojun1998** [comment]
8

**Comment by DarkGost** [comment]
哪里开始

**Comment by yzgyyang** [comment]
@maojun1998 好的，你可以先下一个 PO 编辑器（例如 poedit）熟悉一下操作，然后尝试用其打开
 `projects/books/handbook/zh_CN.po`。稍后我将会把要翻译的行号告诉你。

翻译的话，不用完全自己打，可以参照现有的原文和翻译。如果内容没有过期则可以直接用，否则可以稍微修改一下。
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md#references

**Comment by yzgyyang** [comment]
@maojun1998 需要翻译的行数为 2779-2867，状态已经更新，可以开始了。 😆 
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md

请仔细阅读并且遵循 Style Guide，完成后可以提交 Pull Request。谢谢你的工作！
