### ISSUE TITLE
j3ff: Update 2. Installing FreeBSD (386 - 837)

### ISSUE THREAD

**Issue by yzgyyang** [yzgyyang/freebsd-doc-cn#6]
@cnBSD Which chapter do you want to take on?

For available chapters and current status, please view:
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md

**Comment by cnBSD** [comment]
2. Installing FreeBSD
thx!

**Comment by yzgyyang** [comment]
@cnBSD 好的，你可以先下一个 PO 编辑器（例如 poedit）熟悉一下操作，然后尝试用其打开
 `projects/books/handbook/zh_CN.po`。需要翻译的行数为 386-837，状态已经更新，可以开始了。 😆 

翻译的话，不用完全自己打，可以参照现有的原文和翻译。如果内容没有过期则可以直接用，否则可以稍微修改一下。请仔细阅读并且遵循 Style Guide，完成后可以提交 Pull Request。谢谢你的工作！
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md#references
