### ISSUE TITLE
Kelven: Update 3. FreeBSD Basics (838 - 1503)

### ISSUE THREAD

**Issue by yzgyyang** [yzgyyang/freebsd-doc-cn#8]
@kelvenchi Which chapter do you want to take on?

For available chapters and current status, please view:
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md

**Comment by kelvenchi** [comment]
chapter 3

2017-10-12 19:26 GMT+08:00 Guangyuan (Charlie) Yang <
notifications@github.com>:

**Comment by yzgyyang** [comment]
@kelvenchi 状态已经更新，可以开始了。谢谢你的工作！
https://github.com/yzgyyang/freebsd-doc-cn/blob/master/status/books-handbook.md
